RTAFB-5840 Adapt Script for Service Studio installation
OutSystems/OutSystems.SetupTools pull request #114
Opened 2022-08-03 08:53 UTC by pedromelaos

Adapt Script for Service Studio installation.
Previously It was only possible to install Development Environment,

2022-08-03 09:48 UTC, luisalourenco approved these changes

2022-08-03 10:31 UTC, RSeara approved these changes

2022-08-03 10:32 UTC, smeegoan approved these changes

2022-08-03 12:59 UTC, RSeara requested changes
I'm still validating with the release team some aspects regarding security of the endpoint

2022-08-04 12:37 UTC, RSeara approved these changes

2022-08-04 16:15 UTC, merged