R11BRT-777 .NET 8 Hosting Bundle
OutSystems/OutSystems.SetupTools pull request #123
Opened 2023-12-18 13:13 UTC by ajps28

- Update Hosting Bundle to .NET 8 (8.0.0)
- Adapt unit tests and add new test cases for .NET 8 version
- Refactor unit tests for readability

2024-01-09 16:53 UTC, pedro132 requested changes
Missing a line in `Get-OSServerPreReqs.ps1` when the function is invoked passing the version using only with major (11). Otherwise, minor nitpicks.

2024-01-09 16:53 UTC, pedro132 commented on src/Outsystems.SetupTools/Functions/Get-OSServerPreReqs.ps1
>                      $requireDotNetHostingBundle6 = $true
Like the comment above mentions, if no specific (minor and patch) version is specified, all versions should be checked. Missing version 8.0 here.

2024-01-09 16:53 UTC, pedro132 commented on test/unit/Install-OSServerPreReqs.Tests.ps1
> +            It 'Should not run the .NET 8.0 Hosting Bundle installation' { Assert-MockCalled @assRunInstallDotNetHostingBundle8 }
The sentences of this and the previous lines are incorrect ->
> Should **not** run the .NET 6.0 Hosting Bundle installation

> Should ~~**not**~~ run the .NET 8.0 Hosting Bundle installation

2024-01-09 16:53 UTC, pedro132 commented on test/unit/Install-OSServerPreReqs.Tests.ps1
> +            It 'Should not run the .NET 8.0 Hosting Bundle installation' { Assert-MockCalled @assRunInstallDotNetHostingBundle8 }
Same here.

2024-01-11 12:28 UTC, ajps28 commented on src/Outsystems.SetupTools/Functions/Get-OSServerPreReqs.ps1
>                      $requireDotNetHostingBundle6 = $true
Good catch, corrected now.

2024-01-11 12:30 UTC, ajps28 commented on test/unit/Install-OSServerPreReqs.Tests.ps1
> +            It 'Should not run the .NET 8.0 Hosting Bundle installation' { Assert-MockCalled @assRunInstallDotNetHostingBundle8 }
nice catches, thanks!

2024-01-11 12:30 UTC, ajps28 commented on test/unit/Install-OSServerPreReqs.Tests.ps1
> +            It 'Should not run the .NET 8.0 Hosting Bundle installation' { Assert-MockCalled @assRunInstallDotNetHostingBundle8 }
nice catches, thanks!

2024-01-11 14:43 UTC, pedro132 approved these changes
Ship it :shipit:

2024-01-17 09:56 UTC, merged